### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by GIS243** [worldbank/Pakistan-Poverty-from-Sky#34]
Request for Paper Link

Hi ,

I hope this message finds you well.

Could you please provide me with the link to the paper associated with the repository?

Thanks in advance.

Best regards,

**Comment by ramarty** [comment]
@GIS243 It should be published in the next couple weeks - will let you know when it's published & link to the paper on the repo when it is!

**Comment by GIS243** [comment]
Thanks

**Comment by ramarty** [comment]
@GIS243 Here's the paper!

https://www.nature.com/articles/s41598-023-49564-6
